name: "Deploy Codigo"

on:
  push:
    branches: ["main"] # Trigger

  jobs:
    deploy-codigo:
      runs-on: ubuntu-latest
      steps:
        - run: echo "Hacemos pull del codigo"
        - run: echo "Correr migraciones"
        - run: echo "Generar binario"
        - run: echo "Publicar version"
